sudo: 'required'

services:
  - 'docker'

script:
  - 'docker build -t mahulst/code-challenge-api .'

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ; docker push mahulst/code-challenge-api;

notifications:
  email: false
